#!/bin/bash
#SBATCH --job-name=08_binning
#SBATCH --error=logs/%x-%A_%a.err
#SBATCH --output=logs/%x-%A_%a.out
#SBATCH --partition=general
#SBATCH --qos=regular
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --mem=32000
#SBATCH --array=1-93%25

set -euo pipefail

######################################
# Script: 08_binning.sh
#
# Binning of the contigs generated by 07_genome_assembly.sh
# (data/06.MegahitResults) using three different programs:
#   - MetaBAT2
#   - MaxBin2
#   - CONCOCT
#
# Binning requires per-contig coverage, so the "microbiome" reads of
# each sample (the same ones used by megahit, see
# 07_genome_assembly.sh) are first mapped against that sample's own
# contigs with bowtie2. From that BAM we compute:
#   - depth.txt (jgi_summarize_bam_contig_depths) -> used by MetaBAT2
#     and, after reformatting to 2 columns, also by MaxBin2 (so reads
#     don't need to be mapped twice).
#   - the subcontig coverage table required by CONCOCT
#     (cut_up_fasta.py + concoct_coverage_table.py).
#
# Input:
#   data/06.MegahitResults/<sample>/final.contigs.fa
#   data/03.MicrobiomeReads/<sample>/<sample>_microbiome_R{1,2}.fastq.gz
#
# Output:
#   data/07.BinningResults/<sample>/
#       mapping/<sample>.sorted.bam(.bai)
#       depth.txt
#       metabat2/
#       maxbin2/
#       concoct/
######################################

WORKDIR=$(pwd)

CONTIGS_DIR="$WORKDIR/data/06.MegahitResults"
READS_DIR="$WORKDIR/data/03.MicrobiomeReads"
OUTPUT_DIR="$WORKDIR/data/07.BinningResults"

mkdir -p "$OUTPUT_DIR"
mkdir -p logs

CPU=$SLURM_CPUS_PER_TASK

###############################################################################
# Automatically detect the sample (one subfolder per sample in
# 06.MegahitResults, same scheme as 07_genome_assembly.sh)
###############################################################################

cd "$CONTIGS_DIR"

SAMPLE=$(find . -mindepth 1 -maxdepth 1 -type d | sort | sed -n "${SLURM_ARRAY_TASK_ID}p")
SAMPLE=${SAMPLE#./}

if [[ -z "$SAMPLE" ]]; then
    echo "ERROR: Sample not found."
    exit 1
fi

cd "$WORKDIR"

CONTIGS="$CONTIGS_DIR/$SAMPLE/final.contigs.fa"
R1=$(find "$READS_DIR/$SAMPLE" -maxdepth 1 -name "*_microbiome_R1.fastq.gz" | head -1 || true)
R2=$(find "$READS_DIR/$SAMPLE" -maxdepth 1 -name "*_microbiome_R2.fastq.gz" | head -1 || true)

if [[ ! -f "$CONTIGS" ]]; then
    echo "ERROR: Contigs not found for $SAMPLE"
    echo "$CONTIGS"
    exit 1
fi

if [[ -z "$R1" || -z "$R2" ]]; then
    echo "ERROR: FASTQ files not found for $SAMPLE"
    echo "$READS_DIR/$SAMPLE"
    exit 1
fi

SAMPLE_OUT="$OUTPUT_DIR/$SAMPLE"
MAP_DIR="$SAMPLE_OUT/mapping"
METABAT_DIR="$SAMPLE_OUT/metabat2"
MAXBIN_DIR="$SAMPLE_OUT/maxbin2"
CONCOCT_DIR="$SAMPLE_OUT/concoct"

mkdir -p "$MAP_DIR" "$METABAT_DIR" "$MAXBIN_DIR" "$CONCOCT_DIR"

echo
echo "======================================"
echo "Binning sample: $SAMPLE"
echo "======================================"
echo

###############################################################################
# 1) Map the sample's reads against its own contigs
#    (needed to compute the coverage used by the 3 binners)
###############################################################################

module load Bowtie2/2.5.5-GCC-14.2.0
module load SAMtools/1.18-GCC-12.3.0

BAM="$MAP_DIR/${SAMPLE}.sorted.bam"

if [[ ! -f "$BAM" ]]; then
    INDEX="$MAP_DIR/${SAMPLE}_contigs"
    bowtie2-build --threads "$CPU" "$CONTIGS" "$INDEX"

    bowtie2 \
        --threads "$CPU" \
        -x "$INDEX" \
        -1 "$R1" \
        -2 "$R2" \
        2> "$MAP_DIR/${SAMPLE}.bowtie2.log" \
        | samtools view -@ "$CPU" -b - \
        | samtools sort -@ "$CPU" -o "$BAM"

    samtools index -@ "$CPU" "$BAM"
else
    echo "BAM already exists for $SAMPLE, skipping remapping."
fi

module purge

###############################################################################
# 2) MetaBAT2
###############################################################################

source /home/lchueca/miniforge3/etc/profile.d/conda.sh
conda activate /scratch/lchueca/conda-env/metabat2

DEPTH_FILE="$SAMPLE_OUT/depth.txt"

jgi_summarize_bam_contig_depths --outputDepth "$DEPTH_FILE" "$BAM"

metabat2 \
    -i "$CONTIGS" \
    -a "$DEPTH_FILE" \
    -o "$METABAT_DIR/bin" \
    -t "$CPU"

conda deactivate

###############################################################################
# 3) MaxBin2
#    Reuses MetaBAT2's depth.txt (contigName + totalAvgDepth) instead
#    of mapping the reads again.
###############################################################################

conda activate /scratch/lchueca/conda-env/maxbin2

MAXBIN_ABUND="$SAMPLE_OUT/maxbin_abundance.txt"
tail -n +2 "$DEPTH_FILE" | awk -F'\t' '{print $1"\t"$3}' > "$MAXBIN_ABUND"

run_MaxBin.pl \
    -contig "$CONTIGS" \
    -abund "$MAXBIN_ABUND" \
    -out "$MAXBIN_DIR/bin" \
    -thread "$CPU"

conda deactivate

###############################################################################
# 4) CONCOCT
###############################################################################

conda activate /scratch/lchueca/conda-env/concoct

CONTIGS_CUT="$CONCOCT_DIR/contigs_10K.fa"
BED_CUT="$CONCOCT_DIR/contigs_10K.bed"
COVERAGE_TABLE="$CONCOCT_DIR/coverage_table.tsv"

cut_up_fasta.py "$CONTIGS" -c 10000 -o 0 --merge_last -b "$BED_CUT" > "$CONTIGS_CUT"

concoct_coverage_table.py "$BED_CUT" "$BAM" > "$COVERAGE_TABLE"

concoct \
    --composition_file "$CONTIGS_CUT" \
    --coverage_file "$COVERAGE_TABLE" \
    -b "$CONCOCT_DIR/" \
    -t "$CPU"

merge_cutup_clustering.py "$CONCOCT_DIR/clustering_gt1000.csv" > "$CONCOCT_DIR/clustering_merged.csv"

mkdir -p "$CONCOCT_DIR/fasta_bins"
extract_fasta_bins.py "$CONTIGS" "$CONCOCT_DIR/clustering_merged.csv" --output_path "$CONCOCT_DIR/fasta_bins"

conda deactivate

echo
echo "Binning finished for $SAMPLE (MetaBAT2, MaxBin2, CONCOCT)"
echo
