#!/bin/bash
#SBATCH --job-name=checkm2_multiqc_report
#SBATCH --error=logs/%x-%j.err
#SBATCH --output=logs/%x-%j.out
#SBATCH --partition=general
#SBATCH --qos=regular
#SBATCH --cpus-per-task=6
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --mem=8000

###############################################################################
# Script: checkm2_multiqc_report.sh
#
# Description:
#   Create a MultiQC report for the CheckM2 results generated by 09_MAGScoT.sh.
#
# Usage:
#   sbatch checkm2_multiqc_report.sh
#
###############################################################################
set -euo pipefail

# Load modules
module load Miniforge3/24.11.3-2

# Activate MultiQC environment
conda activate /scratch/lchueca/conda-env/MultiQC


# Directories
WORKDIR=$(pwd)
CHECKM2_DIR="$WORKDIR/data/08.CheckM2Results/checkm2_output"
mkdir -p logs

multiqc -o "$CHECKM2_DIR" "$CHECKM2_DIR" --force